import "./globals.css";
import { Poppins } from "next/font/google";
import { BrowserRouter } from "react-router-dom";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "900", "800", "700", "600", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
